import { ReportTab } from './dashboard.models';

export const reportColumnsByTab: Record<ReportTab, string[]> = {
  CTe: [
    'Data de emissao',
    'Tipo de CTe',
    'Serie do CTe',
    'N CTe',
    'N chave de acesso',
    'N NFe vinculada',
    'Numero do documento',
    'Motorista',
    'Placa / Veiculo',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Remetente',
    'Destinatario',
    'Tomador',
    'UF do tomador',
    'Expedidor',
    'Recebedor',
    'Endereco destinatario',
    'Endereco tomador',
    'Produto predominante',
    'CFOP',
    'Peso da carga',
    'Volumes (unidade)',
    'Litros',
    'Metros cubicos (m3)',
    'Valor da carga',
    'Valor total do servico',
    'Valor a receber',
    'CST',
    'Valor do ICMS',
    'Valor do ICMS ST',
    'Componente: Valor do seguro',
    'Componente: Valor do pedagio',
    'Componente: Valor do frete',
    'Situacao',
    'Situacao no financeiro',
    'Observacoes gerais',
    'Usuario',
    'Hora de emissao',
    'Protocolo de autorizacao',
  ],
  MDFe: [
    'Data de emissao',
    'N MDFe',
    'N NFe vinculada',
    'N CTe vinculado',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Placa do veiculo',
    'Proprietario do veiculo',
    'Motorista',
    'CPF do motorista',
    'Valor do CTe',
    'Valor da NFe',
    'Valor da carga',
    'Peso bruto',
    'Situacao',
    'Usuario',
    'N CIOT',
    'Hora de emissao',
    'Valor do vale-pedagio',
    'Numero do vale-pedagio',
  ],
  Cargas: [
    'N CTe',
    'N da Nota',
    'Chave de acesso da nota',
    'Emitente da nota',
    'Destinatario da nota',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Peso bruto da nota',
    'Valor da nota',
    'Volume',
  ],
};

export const selectedReportColumnsByTabDefault: Record<ReportTab, string[]> = {
  CTe: [
    'Data de emissao',
    'Tipo de CTe',
    'N CTe',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Tomador',
    'Produto predominante',
    'Valor da carga',
    'Valor total do servico',
    'Peso da carga',
    'Situacao',
    'N NFe vinculada',
  ],
  MDFe: [
    'Data de emissao',
    'N MDFe',
    'N NFe vinculada',
    'N CTe vinculado',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Placa do veiculo',
    'Proprietario do veiculo',
    'Motorista',
    'Valor do CTe',
    'Valor da NFe',
    'Valor da carga',
    'Peso bruto',
    'Situacao',
  ],
  Cargas: [
    'N CTe',
    'N da Nota',
    'Destinatario da nota',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Valor da nota',
  ],
};
