import { ReportTab } from './dashboard.models';

export const reportColumnsByTab: Record<ReportTab, string[]> = {
  CTe: [
    'Data de emissão',
    'Tipo de CTe',
    'Série do CTe',
    'N CTe',
    'N chave de acesso',
    'N NFe vinculada',
    'Número do documento',
    'Motorista',
    'Placa / Veículo',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Remetente',
    'Destinatário',
    'Tomador',
    'UF do tomador',
    'Expedidor',
    'Recebedor',
    'Endereço destinatário',
    'Endereço tomador',
    'Produto predominante',
    'CFOP',
    'Peso da carga',
    'Volumes (unidade)',
    'Litros',
    'Metros cúbicos (m³)',
    'Valor da carga',
    'Valor total do serviço',
    'Valor a receber',
    'CST',
    'Valor do ICMS',
    'Valor do ICMS ST',
    'Componente: Valor do seguro',
    'Componente: Valor do pedágio',
    'Componente: Valor do frete',
    'Situação',
    'Situação no financeiro',
    'Observações gerais',
    'Usuário',
    'Hora de emissão',
    'Protocolo de autorização',
  ],
  MDFe: [
    'Data de emissão',
    'N MDFe',
    'N NFe vinculada',
    'N CTe vinculado',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Placa do veículo',
    'Proprietário do veículo',
    'Motorista',
    'CPF do motorista',
    'Valor do CTe',
    'Valor da NFe',
    'Valor da carga',
    'Peso bruto',
    'Situação',
    'Usuário',
    'N CIOT',
    'Hora de emissão',
    'Valor do vale-pedágio',
    'Número do vale-pedágio',
  ],
  Cargas: [
    'N CTe',
    'N da Nota',
    'Chave de acesso da nota',
    'Emitente da nota',
    'Destinatário da nota',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Peso bruto da nota',
    'Valor da nota',
    'Volume',
  ],
};

export const selectedReportColumnsByTabDefault: Record<ReportTab, string[]> = {
  CTe: [
    'Data de emissão',
    'Tipo de CTe',
    'N CTe',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Tomador',
    'Produto predominante',
    'Valor da carga',
    'Valor total do serviço',
    'Peso da carga',
    'Situação',
    'N NFe vinculada',
  ],
  MDFe: [
    'Data de emissão',
    'N MDFe',
    'N NFe vinculada',
    'N CTe vinculado',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Placa do veículo',
    'Proprietário do veículo',
    'Motorista',
    'Valor do CTe',
    'Valor da NFe',
    'Valor da carga',
    'Peso bruto',
    'Situação',
  ],
  Cargas: [
    'N CTe',
    'N da Nota',
    'Destinatário da nota',
    'Cidade de origem',
    'Cidade de destino',
    'UF',
    'Valor da nota',
  ],
};
